search page and search component
andjela-kostic/yasm-fe pull request #2
Opened 2022-11-04 13:46 UTC by andjela-kostic

2022-11-04 14:21 UTC, IgorBGD92 approved these changes

2022-11-07 10:00 UTC, cerovacad requested changes

2022-11-07 10:00 UTC, cerovacad commented on src/styles/search/search.scss
> +#search-head-container {
ps change all ids ti classes

2022-11-07 10:00 UTC, cerovacad commented on src/components/Search.tsx
> +  function choseOptions(emp: Employee) {
pls use arrow functions instead of regular ones

2022-11-07 13:10 UTC, cerovacad approved these changes

2022-11-07 13:10 UTC, cerovacad commented on src/styles/search/search.css
> +@import url("../variables/variables.scss");
remove this css file pls

2022-11-07 13:10 UTC, cerovacad commented on src/styles/search/search.scss
>  * {
remove this css file pls

2022-11-07 13:40 UTC, merged